#!/bin/sh -e

if [ upgrade != "$1" ] || dpkg --compare-versions "$2" lt 5-33
then
	if [ -z "$(dpkg-divert --list /usr/share/mime/packages/Nokia-QtCreator.xml)" ]
	then
		dpkg-divert --add --rename --divert \
		    /usr/share/mime/packages/Nokia-QtCreator.xml.bak \
		    /usr/share/mime/packages/Nokia-QtCreator.xml
    fi
fi

exit 0

