#!/bin/sh -e
# This script can be called in the following ways:
#
# After the package was removed:
#       <postrm> remove
#
# After the package was purged:
#       <postrm> purge
#
# After the package was upgraded:
#       <old-postrm> upgrade <new-version>
# if that fails:
#       <new-postrm> failed-upgrade <old-version>
#
#
# After all of the packages files have been replaced:
#       <postrm> disappear <overwriting-package> <version>
#
#
# If preinst fails during install:
#       <new-postrm> abort-install
#
# If preinst fails during upgrade of removed package:
#       <new-postrm> abort-install <old-version>
#
# If preinst fails during upgrade:
#       <new-postrm> abort-upgrade <old-version>


case "$1" in

remove)

	update-alternatives --remove vtrgb /etc/vtrgb-gnome
	
;;

esac

# Automatically added by dh_installsystemd/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'setvtrgb.service' >/dev/null || true
fi
# End automatically added section

exit 0
