#!/bin/sh -e

case "$1" in

configure)

    if [ -d /run/systemd/system ] && [ "$(systemctl is-active cups.service)" = 'active' ]
    then
        /usr/local/bin/printer-update
    fi

;;

esac


exit 0
