#!/bin/sh -e

case "$1" in

remove)

    if [ "$(LC_ALL=C update-alternatives --query x-cursor-theme 2>/dev/null | grep "^Status:\|^Value:" | cut -d ' ' -f 2- | tr '\n' ' ')" = 'manual /etc/X11/cursors/breeze_cursors.theme ' ]
    then
	    update-alternatives --auto x-cursor-theme
	fi
;;

esac


exit 0
