#!/bin/sh -e

case "$1" in

configure)
    
    ## Make git save credentials by default ------------------------------------
    
	git config --system credential.helper store
	
    ## Set default pull startegy -----------------------------------------------

    git config --system pull.ff only

    ## Set default branch name -------------------------------------------------

    git config --system init.defaultBranch master
    
    ## Add alias for rebase but keep committer information ---------------------
    
    git config --system alias.rebasekeep "-c rebase.instructionFormat='%s%nexec GIT_COMMITTER_NAME=\"%cN\" GIT_COMMITTER_EMAIL=\"%ce\" GIT_COMMITTER_DATE=\"%cd\" git commit --amend --no-edit --date=\"%ad\"' rebase"
;;

esac


exit 0
