#!/bin/sh -e
# This script can be called in the following ways:
#
# After the package was removed:
#       <postrm> remove
#
# After the package was purged:
#       <postrm> purge
#
# After the package was upgraded:
#       <old-postrm> upgrade <new-version>
# if that fails:
#       <new-postrm> failed-upgrade <old-version>
#
#
# After all of the packages files have been replaced:
#       <postrm> disappear <overwriting-package> <version>
#
#
# If preinst fails during install:
#       <new-postrm> abort-install
#
# If preinst fails during upgrade of removed package:
#       <new-postrm> abort-install <old-version>
#
# If preinst fails during upgrade:
#       <new-postrm> abort-upgrade <old-version>


case "$1" in

remove)

	if which update-ca-certificates >/dev/null 2>&1
	then
	    update-ca-certificates
	fi

;;

esac


exit 0
