#!/bin/sh -e

case "$1" in

configure)
    
	update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/rczi/rczi.plymouth 175 \
	                    --slave   /usr/share/plymouth/themes/default.grub default.plymouth.grub /usr/share/plymouth/themes/rczi/rczi.grub

	if which update-initramfs >/dev/null 2>&1
	then
	    update-initramfs -u
	fi
	
	if [ -e /boot/grub/grub.cfg ] && which update-grub2 >/dev/null 2>&1
	then
	    update-grub2
	fi
	
;;

esac


exit 0
