#!/bin/sh -e

case "$1" in
    configure)
	update-alternatives \
		--install /usr/share/plymouth/themes/default.plymouth default.plymouth \
		/usr/share/plymouth/themes/rczi/rczi.plymouth 175

	if which update-initramfs >/dev/null 2>&1
	then
	    update-initramfs -u
	fi
	;;
esac


exit 0
